apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-fat0
  namespace: mprpic-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:aad3f9d287116437c480422604da9fe8067953faabcba053c4e1abc56b38a0eb
        name: my-python
        resources: {}
status: {}
